"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
a = 1 # Initialise A
b = 2 # Initialise B
c = 0 # Initialise C
res = 2 # Initialise the running result
while a+b < 4000000: # Repear if the next fibonacci number will be less than 4000000
    c = a+b # Add a and b and store it in c
    if c%2 == 0: # Check if the new fibonacci number is even
        res+=c # If even add it to the result
    a=b # Set B to A
    b=c # Set C to B
print(res) # Print the value in result